### ISSUE TITLE
Nexus Updates Crashes Quick Config Tool

### ISSUE THREAD

**Issue by jashoewa** [FelisDiligens/Fallout76-QuickConfiguration#12]
When trying to update nexus mod information in the mod manager I get the following error message and the mod manager and quick config tool crashes.

[F76QC Error.txt](https://github.com/FelisDiligens/Fallout76-QuickConfiguration/files/9228116/F76QC.Error.txt)

**Comment by FelisDiligens** [comment]
Should be fixed now.
[Relevant commit](https://github.com/FelisDiligens/Fallout76-QuickConfiguration/commit/f83e5ee2018eb27d9dd8d27b9b006dc33a83d547)
