### ISSUE TITLE
Crash on Open Vrs. 1.12.2

### ISSUE THREAD

**Issue by Athae1218** [FelisDiligens/Fallout76-QuickConfiguration#16]
*************** Error message ***************
System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: Summary, Mod, Mods. Line 124, position 274.

**************** System Info ****************
Operating system:  Windows 10 64-bit
Program version:   1.12.2
User agent:        Fo76QuickConfiguration/1.12.2 (Windows NT 10.0.19044.0; x64) .NETFramework/4.7.2
Running as admin:  No
System culture:    English (United States)
App locale:        en-US
Game edition:      Unknown

**************** Stack Trace ****************
If any files are listed (like "at ... in ...\*.cs:line 123"):
Those are files on *my* computer, so don't worry if you can't find them.

System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: Summary, Mod, Mods. Line 124, position 274.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Fo76ini.NexusAPI.NexusMods.Load() in D:\Workspace\Fallout76-QuickConfiguration\Fo76ini\NexusAPI\NexusMods.cs:line 91
   at Fo76ini.Initialization.InitApp() in D:\Workspace\Fallout76-QuickConfiguration\Fo76ini\Initialization.cs:line 46
   at Fo76ini.Program.Main() in D:\Workspace\Fallout76-QuickConfiguration\Fo76ini\Program.cs:line 56

**Comment by Bealze** [comment]
I two have had this issue only way to run the app is to run install anytime i want to open it.

*************** Error message ***************Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.**************** System Info ****************Operating system:  Windows 11 64-bitProgram version:   1.12.0User agent:        Fo76QuickConfiguration/1.12.0 (Windows NT 10.0.22621.0; x64) .NETFramework/4.7.2Running as admin:  YesSystem culture:    English (United States)App locale:        en-USGame edition:      Steam**************** Stack Trace ****************If any files are listed (like "at ... in ...\*.cs:line 123"):Those are files on *my* computer, so don't worry if you can't find them.Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.   at Newtonsoft.Json.JsonTextReader.ParseValue()   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)   at Fo76ini.Forms.FormMain.Tabs.UserControlHome.ScrapeServerStatus() in .\Forms\FormMain\Views\UserControlHome.cs:line 273   at Fo76ini.Forms.FormMain.Tabs.UserControlHome.backgroundWorkerScrapeServerStatus_DoWork(Object sender, DoWorkEventArgs e) in .\Forms\FormMain\Views\UserControlHome.cs:line 401   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by FelisDiligens** [comment]
A bit late but here we go:

- The issue @Athae1218 reported should be fixed now (in v1.12.3).
- The issue @Bealze reported has already been fixed in v1.12.1.

Thanks for reporting! 👍🏻
