### ISSUE TITLE
Can no longer edit Resource List manually

### ISSUE THREAD

**Issue by luccasfs** [FelisDiligens/Fallout76-QuickConfiguration#19]
Even by hitting apply changes, when the manager is closed and opened again it goes back to the manager default, the version prior to the newest one didn't do that, had to reinstall the old version

**Comment by FelisDiligens** [comment]
Hi, thanks for reporting!
I found the bug and will push an update soon.

**Comment by FelisDiligens** [comment]
Update is out now, let me know if there are any more issues.
